export default interface ParamProposalTable {
  max_bh_size: `${number}` | null
  min_pool_cost: `${number}` | null
  min_fee_b: `${number}` | null
  influence: number | null
  min_fee_ref_script_cost_per_byte: number | null
  dvt_committee_normal: number | null
  treasury_growth_rate: number | null
  dvt_p_p_technical_group: number | null
  dvt_p_p_gov_group: number | null
  pvtpp_security_group: number | null
  pvt_hard_fork_initiation: number | null
  price_mem: number | null
  max_collateral_inputs: number | null
  protocol_minor: number | null
  pvt_committee_no_confidence: number | null
  gov_action_deposit: `${number}` | null
  max_tx_ex_steps: `${number}` | null
  price_step: number | null
  max_tx_ex_mem: `${number}` | null
  min_utxo_value: `${number}` | null
  epoch_no: number | null
  optimal_pool_count: `${number}` | null
  pool_deposit: `${number}` | null
  coins_per_utxo_size: `${number}` | null
  protocol_major: number | null
  collateral_percent: number | null
  entropy: Buffer | null
  registered_tx_id: bigint
  dvt_motion_no_confidence: number | null
  max_epoch: `${number}` | null
  dvt_p_p_economic_group: number | null
  committee_min_size: `${number}` | null
  id: bigint
  drep_deposit: `${number}` | null
  dvt_p_p_network_group: number | null
  cost_model_id: bigint | null
  pvt_committee_normal: number | null
  min_fee_a: `${number}` | null
  drep_activity: `${number}` | null
  decentralisation: number | null
  max_tx_size: `${number}` | null
  key_deposit: `${number}` | null
  pvt_motion_no_confidence: number | null
  monetary_expand_rate: number | null
  key: Buffer | null
  dvt_hard_fork_initiation: number | null
  max_block_ex_mem: `${number}` | null
  dvt_treasury_withdrawal: number | null
  max_val_size: `${number}` | null
  max_block_ex_steps: `${number}` | null
  max_block_size: `${number}` | null
  dvt_committee_no_confidence: number | null
  dvt_update_to_constitution: number | null
  gov_action_lifetime: `${number}` | null
  committee_max_term_length: `${number}` | null
}
